language : "pt"
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
    features:
      - - low
        - title
      - - bias
        - prefix2
        - digit
        - suffix2
      - - suffix5
  - name: DucklingHTTPExtractor
    url: http://duckling:8000
    locale: pt_BR
    dimensions:
      - phone-number
      - email
      - amount-of-money
      - number
      - distance
    timezone: America/Sao_Paulo
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
  - name: EmbeddingIntentClassifier
    intent_tokenization_flag: true
    intent_split_symbol: +

policies:
  - name: KerasPolicy
    max_history: 10
    core_threshold: 0.4
    nlu_threshold: 0.3
    rnn_size: 16
    epochs: 50
    state_featurizer:
      - name: LabelTokenizerSingleStateFeaturizer
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: FormPolicy
